### ISSUE TITLE
Build on `linux_aarch64`

### ISSUE THREAD

**Issue by chrisjsewell** [conda-forge/rabbitmq-server-feedstock#67]
### Comment:

Heya, would it be possible to also have this build target?

**Comment by ndevenish** [comment]
Unfortunately, it looks like the upstream erlang feedstock https://github.com/conda-forge/erlang-feedstock doesn't support aarch64 yet.

It does look like arch linux has managed to package for aarch64: https://archlinuxarm.org/packages/aarch64/rabbitmq, so if this ever changes there is at least evidence that it's possible to do so.

**Comment by danielhollas** [comment]
@ndevenish would you mind reopening this issue, since the build on "linux_aarch64" is not available atm? We are still very much interested in this, as it would simplify our Docker pipeline a lot. Thanks!

**Comment by ndevenish** [comment]
I'm happy to have this open and pending, but unless https://github.com/conda-forge/erlang-feedstock starts packaging linux_aarch64 there isn't a lot that we can do here.

**Comment by danielhollas** [comment]
Thanks! I've opened a corresponding issue there as well for tracking. https://github.com/conda-forge/erlang-feedstock/issues/154

**Comment by jakirkham** [comment]
Also would follow [the same steps]( https://conda-forge.org/docs/maintainer/knowledge_base/#using-arch_rebuildtxt ) we used with `erlang` for `rabbitmq-server`

**Comment by jakirkham** [comment]
Have just merged in Daniel's work on `erlang` to add other architectures for Linux and macOS:

* https://github.com/conda-forge/erlang-feedstock/pull/159
* https://github.com/conda-forge/erlang-feedstock/pull/162

Those packages should soon be available

Also have added `rabbitmq-server` to the arch migrator ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6071 ). So there should soon be a bot PR enabling arch builds here

Potentially there may be a bit more work depending on how that goes

**Comment by danielhollas** [comment]
@jakirkham thanks so much for merging and initiating the migration bot for this repo!

I think there is one more step in the Erlang repo. There is currently no rabbitmq-server version that supports Erlang 27. If I understand the process correctly we'll need to create a new 26.x branch and  backport the changes? LMK if you want me to help with that.

**Comment by jakirkham** [comment]
Tried to squash and rebase the changes keeping you as author in PR: https://github.com/conda-forge/erlang-feedstock/pull/163

Let's see if that is enough. If not, please feel free to pick it up

**Comment by jakirkham** [comment]
Looks like that did the trick. Packages are uploaded (though may still be mirroring on CDN)
